var CALENDAR_ID="adange@asu.edu",TZ="America/Phoenix",OFFSET="-07:00",START=8,END=19,BUFFER=15,LEAD=86400000;
var TOPICS=["Job or consulting opportunity","Portfolio feedback","Career or networking conversation","Collaboration or project opportunity","Other"];
function doGet(e){try{if(e.parameter.action!=="availability")throw Error("Unknown action");var y=+e.parameter.year,m=+e.parameter.month,d=duration_(e.parameter.duration);if(!Number.isInteger(y)||y<2020||y>2100||!Number.isInteger(m)||m<0||m>11)throw Error("Invalid date");return json_({slots:availability_(y,m,d)})}catch(x){return json_({error:message_(x)})}}
function doPost(e){try{var i=JSON.parse(e.postData&&e.postData.contents||"{}");if(i.action!=="booking")throw Error("Unknown action");if(i.website)return json_({ok:true,startIso:i.startIso,meetLink:null});var d=validate_(i),lock=LockService.getScriptLock();lock.waitLock(15000);try{if(!free_(d.startIso,d.duration))return json_({ok:false,error:"That time was just taken. Please pick another slot."});return json_(create_(d))}finally{lock.releaseLock()}}catch(x){return json_({ok:false,error:message_(x)})}}
function validate_(i){var n=String(i.name||"").trim(),e=String(i.email||"").trim(),s=String(i.startIso||"").trim(),t=String(i.topic||"").trim(),o=String(i.notes||"").trim().slice(0,1000);if(!n||n.length>100)throw Error("Name is required (max 100 chars)");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)||e.length>200)throw Error("Please enter a valid email");if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}-07:00$/.test(s))throw Error("Invalid start time");if(TOPICS.indexOf(t)<0)throw Error("Please select a discussion topic");return{name:n,email:e,startIso:s,duration:duration_(i.duration),topic:t,notes:o}}
function duration_(v){v=+v;if(v!==15&&v!==45)throw Error("Invalid duration (must be 15 or 45)");return v}
function nowParts_(){var n=new Date;return{year:+Utilities.formatDate(n,TZ,"yyyy"),month:+Utilities.formatDate(n,TZ,"M")-1}}
function range_(y,m){y+=Math.floor(m/12);m=((m%12)+12)%12;var nm=m+1,ny=y+Math.floor(nm/12);nm%=12;return{start:new Date(y+"-"+pad_(m+1)+"-01T00:00:00"+OFFSET),end:new Date(ny+"-"+pad_(nm+1)+"-01T00:00:00"+OFFSET)}}
function window_(){var n=nowParts_();return{start:new Date(Date.now()+LEAD),end:range_(n.year,n.month+2).end}}
function clamp_(y,m){var n=nowParts_(),v=y*12+m,min=n.year*12+n.month,max=min+2,c=Math.min(Math.max(v,min),max);return{year:Math.floor(c/12),month:c%12}}
function busy_(a,b){var r=Calendar.Freebusy.query({timeMin:a.toISOString(),timeMax:b.toISOString(),timeZone:TZ,items:[{id:CALENDAR_ID}]}),list=r.calendars[CALENDAR_ID]&&r.calendars[CALENDAR_ID].busy||[];return list.map(function(x){return{start:new Date(x.start).getTime()-BUFFER*60000,end:new Date(x.end).getTime()+BUFFER*60000}})}
function overlap_(a,b,list){return list.some(function(x){return a<x.end&&b>x.start})}
function availability_(y,m,d){var c=clamp_(y,m),r=range_(c.year,c.month),w=window_(),a=new Date(Math.max(r.start,w.start)),b=new Date(Math.min(r.end,w.end));if(a>=b)return{};var busy=busy_(a,b),step=d===15?15:30,days=new Date(Date.UTC(c.year,c.month+1,0)).getUTCDate(),out={};for(var day=1;day<=days;day++){var dow=new Date(Date.UTC(c.year,c.month,day)).getUTCDay();if(dow===0||dow===6)continue;var ymd=c.year+"-"+pad_(c.month+1)+"-"+pad_(day),slots=[];for(var mins=START*60;mins+d<=END*60;mins+=step){var hm=pad_(Math.floor(mins/60))+":"+pad_(mins%60),s=new Date(ymd+"T"+hm+":00"+OFFSET),e=new Date(s.getTime()+d*60000);if(s<w.start||e>w.end||overlap_(s.getTime(),e.getTime(),busy))continue;slots.push(hm)}if(slots.length)out[ymd]=slots}return out}
function free_(iso,d){var s=new Date(iso),e=new Date(s.getTime()+d*60000),w=window_();if(s<w.start||e>w.end)return false;var dow=+Utilities.formatDate(s,TZ,"u"),mins=+Utilities.formatDate(s,TZ,"H")*60+(+Utilities.formatDate(s,TZ,"m"));if(dow>5||mins<START*60||mins+d>END*60)return false;return!overlap_(s.getTime(),e.getTime(),busy_(new Date(s.getTime()-BUFFER*60000),new Date(e.getTime()+BUFFER*60000)))}
function create_(d){var s=new Date(d.startIso),e=new Date(s.getTime()+d.duration*60000),first=html_(d.name.split(/\s+/)[0]||"there"),desc=["<p>Hi "+first+",</p>","<p>Thanks so much for booking a call through my portfolio! I&rsquo;m really excited to connect.</p>","<p>The Google Meet link and time are included in this calendar invite. If there is anything specific you&rsquo;d like to discuss, or any materials you want me to look over beforehand, please feel free to send them my way.</p>","<p>Looking forward to speaking soon!</p>","<p>Best,</p>",'<p>Apurva Dange<br>AI Product Manager | Product Strategist<br><a href="https://www.linkedin.com/in/apurvadange/">LinkedIn</a></p>'].join(""),event={summary:d.duration+" min — Apurva × "+d.name,description:desc,start:{dateTime:d.startIso,timeZone:TZ},end:{dateTime:e.toISOString(),timeZone:TZ},attendees:[{email:d.email,displayName:d.name}],reminders:{useDefault:true},conferenceData:{createRequest:{requestId:"booking-"+s.getTime()+"-"+Utilities.getUuid(),conferenceSolutionKey:{type:"hangoutsMeet"}}},extendedProperties:{private:{bookingTopic:d.topic,bookingNotes:d.notes||""}}},made=Calendar.Events.insert(event,CALENDAR_ID,{conferenceDataVersion:1,sendUpdates:"all"}),meet=made.hangoutLink||null;if(!meet&&made.conferenceData&&made.conferenceData.entryPoints){var v=made.conferenceData.entryPoints.filter(function(x){return x.entryPointType==="video"})[0];meet=v?v.uri:null}return{ok:true,startIso:d.startIso,meetLink:meet,eventId:made.id,htmlLink:made.htmlLink}}
function html_(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;")}function pad_(n){return String(n).padStart(2,"0")}function message_(e){return e&&e.message?e.message:"The booking service is unavailable."}function json_(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON)}
