import{FormEvent,ReactNode,useEffect,useMemo,useState}from"react";
import{Calendar,Check,ChevronLeft,ChevronRight,Clock,Video}from"lucide-react";
import{createBooking,Duration,getAvailability,Slots}from"./api";import{formatDateLong,formatTime12,MONTHS,phoenixTodayParts}from"./date";
const TOPICS=["Job or consulting opportunity","Portfolio feedback","Career or networking conversation","Collaboration or project opportunity","Other"];const DAYS=["S","M","T","W","T","F","S"];const PORTFOLIO="https://apurva-dange.github.io/apurva-showcase-hub/";
export default function App(){const today=phoenixTodayParts();const[topic,setTopic]=useState(""),[notes,setNotes]=useState(""),[duration,setDuration]=useState<Duration|null>(null),[year,setYear]=useState(today.year),[month,setMonth]=useState(today.month),[date,setDate]=useState<string|null>(null),[time,setTime]=useState<string|null>(null),[name,setName]=useState(""),[email,setEmail]=useState(""),[website,setWebsite]=useState(""),[slots,setSlots]=useState<Slots>({}),[loading,setLoading]=useState(false),[booking,setBooking]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState<{startIso:string;meetLink:string|null}|null>(null);const idx=year*12+month,min=today.year*12+today.month,max=min+2;
useEffect(()=>{if(!duration)return;let dead=false;setLoading(true);setError("");getAvailability(year,month,duration).then(r=>{if(!dead)setSlots(r.slots)}).catch((e:Error)=>{if(!dead){setSlots({});setError(e.message)}}).finally(()=>{if(!dead)setLoading(false)});return()=>{dead=true}},[duration,year,month]);
function move(n:number){const next=idx+n;setYear(Math.floor(next/12));setMonth(next%12);setDate(null);setTime(null)}
function reset(){setTopic("");setNotes("");setDuration(null);setDate(null);setTime(null);setName("");setEmail("");setWebsite("");setSlots({});setError("");setSuccess(null)}
async function submit(e:FormEvent){e.preventDefault();if(!topic||!duration||!date||!time)return;setBooking(true);setError("");const startIso=`${date}T${time}:00-07:00`;try{const r=await createBooking({name:name.trim(),email:email.trim(),startIso,duration,topic,notes:notes.trim()||undefined,website});if(!r.ok||!r.startIso)throw new Error(r.error||"Booking failed. Please try again.");setSuccess({startIso:r.startIso,meetLink:r.meetLink??null})}catch(e){setError(e instanceof Error?e.message:"Booking failed. Please try again.")}finally{setBooking(false)}}
return <div className="app"><header><a className="brand" href={PORTFOLIO}>Apurva Dange</a></header><main><p className="eyebrow">Let's Talk</p><h1>Book a call.</h1>{success&&duration?<Success duration={duration} name={name} email={email} data={success} reset={reset}/>:<div className="steps">
<section><Step n={1}>What would you like to discuss?</Step><p className="muted">Please share a brief overview so I can prepare for our conversation.</p><div className="card form"><Field label="Discussion topic"><select required value={topic} onChange={e=>{setTopic(e.target.value);setDuration(null);setDate(null);setTime(null)}}><option value="" disabled>Select a topic…</option>{TOPICS.map(t=><option key={t}>{t}</option>)}</select></Field>{topic==="Other"&&<Field label="Anything specific you'd like me to know? (optional)"><textarea rows={3} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="A sentence or two of context helps me prep."/></Field>}</div></section>
{topic&&<section><Step n={2}>Meeting length</Step><div className="durations">{([{v:15,t:"15min",s:"Intro chat — quick hello, mutual fit."},{v:45,t:"45min",s:"Deep dive — role, product, walk through my work."}]as const).map(o=><button type="button" key={o.v} className={`card duration ${duration===o.v?"active":""}`} onClick={()=>{setDuration(o.v);setDate(null);setTime(null)}}><strong>{o.t}</strong><span>{o.s}</span></button>)}</div></section>}
{topic&&duration&&<section><Step n={3}>Pick a date and time</Step><div className="calendar-layout"><CalendarBox year={year} month={month} prev={()=>move(-1)} next={()=>move(1)} canPrev={idx>min} canNext={idx<max} slots={slots} selected={date} choose={d=>{setDate(d);setTime(null)}} loading={loading} error={!!error}/><div className="card times"><strong>{date?formatDateLong(date):"Pick a date"}</strong>{!date?<p>Available times appear here.</p>:!(slots[date]?.length)?<p>No slots on this day.</p>:<div>{slots[date].map(t=><button type="button" key={t} className={time===t?"selected":""} onClick={()=>setTime(t)}>{formatTime12(t)}</button>)}</div>}</div></div></section>}
{topic&&duration&&date&&time&&<section><Step n={4}>Your details</Step><form className="card details" onSubmit={submit}><div className="summary"><span><Clock size={16}/>{duration} min</span><span><Calendar size={16}/>{formatDateLong(date)}</span><span><Video size={16}/>{formatTime12(time)} MST</span></div><div className="detail-grid"><Field label="Your name"><input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="First and Last Name"/></Field><Field label="Email"><input required type="email" maxLength={200} value={email} onChange={e=>setEmail(e.target.value)} placeholder="hello@yourdomain.com"/></Field></div><label className="trap">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={booking}>{booking?"Booking...":"Confirm booking"}</button><p className="fine">A Google Meet link will be included in the calendar invite sent to your email.</p></form></section>}
</div>}</main></div>}
function Step({n,children}:{n:number;children:ReactNode}){return <div className="step"><span>{n}</span><h2>{children}</h2></div>};function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function CalendarBox(p:{year:number;month:number;prev:()=>void;next:()=>void;canPrev:boolean;canNext:boolean;slots:Slots;selected:string|null;choose:(s:string)=>void;loading:boolean;error:boolean}){const cells=useMemo(()=>{const a:Array<{d:number;y:string}|null>=Array(new Date(Date.UTC(p.year,p.month,1)).getUTCDay()).fill(null),days=new Date(Date.UTC(p.year,p.month+1,0)).getUTCDate();for(let d=1;d<=days;d++)a.push({d,y:`${p.year}-${String(p.month+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`});return a},[p.year,p.month]);return <div className="card calendar"><div className="month"><strong>{MONTHS[p.month]} {p.year}</strong><div><button type="button" onClick={p.prev} disabled={!p.canPrev} aria-label="Previous month"><ChevronLeft size={16}/></button><button type="button" onClick={p.next} disabled={!p.canNext} aria-label="Next month"><ChevronRight size={16}/></button></div></div><div className="weekdays">{DAYS.map((d,i)=><span key={i}>{d}</span>)}</div><div className="days">{cells.map((c,i)=>c?<button type="button" key={c.y} disabled={!p.slots[c.y]?.length} className={p.selected===c.y?"selected":""} onClick={()=>p.choose(c.y)}>{c.d}</button>:<span key={i}/>)}</div>{p.loading&&<p className="status">Loading availability…</p>}{p.error&&!p.loading&&<p className="error">Couldn't load availability. Try again.</p>}</div>}
function Success({duration,name,email,data,reset}:{duration:Duration;name:string;email:string;data:{startIso:string;meetLink:string|null};reset:()=>void}){const d=data.startIso.slice(0,10),t=data.startIso.slice(11,16);return <div className="card success"><i><Check size={20}/></i><h2>You're booked, {name.split(" ")[0]}.</h2><p>A calendar invite with the Google Meet link is on its way to <em>{email}</em>.</p><dl><Row l="When">{formatDateLong(d)} · {formatTime12(t)} MST</Row><Row l="Length">{duration} minutes</Row><Row l="Meet link">{data.meetLink?<a href={data.meetLink} target="_blank" rel="noreferrer">{data.meetLink}</a>:"In your calendar invite"}</Row></dl><div className="actions"><button className="primary" onClick={reset}>Book another time</button></div></div>};function Row({l,children}:{l:string;children:ReactNode}){return <div><dt>{l}</dt><dd>{children}</dd></div>}
